apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mqtt-source
  name: mqtt-source
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: mqtt-source
    spec:
      containers:
      - image: lreimer/mqtt-source:1.0
        name: mqtt-source
        ports:
        - containerPort: 8080
      restartPolicy: Always
