apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: location-processor
  name: location-processor
spec:
  type: NodePort
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: location-processor
