apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: csv-source
  name: csv-source
spec:
  type: NodePort
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: csv-source
