apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: hazelcast-payara
  name: hazelcast-payara
spec:
  type: NodePort
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: hazelcast-payara
