apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: eclipse-mosquitto
  name: eclipse-mosquitto
spec:
  ports:
  - name: "1883"
    port: 1883
    targetPort: 1883
  - name: "9001"
    port: 9001
    targetPort: 9001
  selector:
    io.kompose.service: eclipse-mosquitto
